package com.ollum.mazecape.Arrays;

public class Movement {
    public static final String[] MOVE_DOWN = {
            "bud",
            "cdn", "cdl", "ctu", "cdr", "cud", "ctr", "ctl", "ccs",
            "ddn", "ddl", "dtu", "ddr", "dud", "dtr", "dtl", "dcs",
            "fdn", "fdl", "ftu", "fdr", "fud", "ftr", "ftl", "fcs",
            "idn", "idl", "itu", "idr", "iud", "itr", "itl", "ics",
            "jdn", "jtl", "jtr", "jrd", "jld", "jcd", "jcl", "jcr",
            "ldn", "ldl", "ltu", "ldr", "lud", "ltr", "ltl", "lcs",
            "ndn", "ndl", "ntu", "ndr", "nud", "ntr", "ntl", "ncs",
            "pdn", "pdl", "ptu", "pdr", "pud", "ptr", "ptl", "pcs",
            "sdn", "sdl", "stu", "sdr", "sud", "str", "stl", "scs",
            "vdn", "vdl", "vtu", "vdr", "vud", "vtr", "vtl", "vcs",
            "wdn", "wdl", "wtu", "wdr", "wud", "wtr", "wtl", "wcs",
            "xdn", "xdl", "xtu", "xdr", "xud", "xtr", "xtl", "xcs",
            "ydn", "ydl", "ytu", "ydr", "yud", "ytr", "ytl", "ycs",
            "zdn", "zdl", "ztu", "zdr", "zud", "ztr", "ztl", "zcs",
    };
    public static final String[] MOVE_LEFT = {
            "blr",
            "cdl", "ctu", "clt", "clr", "ctr", "cul", "ctd", "ccs",
            "ddl", "dtu", "dlt", "dlr", "dtr", "dul", "dtd", "dcs",
            "fdl", "ftu", "flt", "flr", "ftr", "ful", "ftd", "fcs",
            "idl", "itu", "ilt", "ilr", "itr", "iul", "itd", "ics",
            "jlt", "jtu", "jtd", "jdl", "jul", "jcd", "jcl", "jcu",
            "ldl", "ltu", "llt", "llr", "ltr", "lul", "ltd", "lcs",
            "ndl", "ntu", "nlt", "nlr", "ntr", "nul", "ntd", "ncs",
            "pdl", "ptu", "plt", "plr", "ptr", "pul", "ptd", "pcs",
            "sdl", "stu", "slt", "slr", "str", "sul", "std", "scs",
            "vdl", "vtu", "vlt", "vlr", "vtr", "vul", "vtd", "vcs",
            "wdl", "wtu", "wlt", "wlr", "wtr", "wul", "wtd", "wcs",
            "xdl", "xtu", "xlt", "xlr", "xtr", "xul", "xtd", "xcs",
            "ydl", "ytu", "ylt", "ylr", "ytr", "yul", "ytd", "ycs",
            "zdl", "ztu", "zlt", "zlr", "ztr", "zul", "ztd", "zcs",
    };
    public static final String[] MOVE_RIGHT = {
            "blr",
            "ctu", "cdr", "clr", "crt", "ctl", "ctd", "cur", "ccs",
            "dtu", "ddr", "dlr", "drt", "dtl", "dtd", "dur", "dcs",
            "ftu", "fdr", "flr", "frt", "ftl", "ftd", "fur", "fcs",
            "itu", "idr", "ilr", "irt", "itl", "itd", "iur", "ics",
            "jrt", "jtu", "jtd", "jdr", "jur", "jcd", "jcu", "jcr",
            "ltu", "ldr", "llr", "lrt", "ltl", "ltd", "lur", "lcs",
            "ntu", "ndr", "nlr", "nrt", "ntl", "ntd", "nur", "ncs",
            "ptu", "pdr", "plr", "prt", "ptl", "ptd", "pur", "pcs",
            "stu", "sdr", "slr", "srt", "stl", "std", "sur", "scs",
            "vtu", "vdr", "vlr", "vrt", "vtl", "vtd", "vur", "vcs",
            "wtu", "wdr", "wlr", "wrt", "wtl", "wtd", "wur", "wcs",
            "xtu", "xdr", "xlr", "xrt", "xtl", "xtd", "xur", "xcs",
            "ytu", "ydr", "ylr", "yrt", "ytl", "ytd", "yur", "ycs",
            "ztu", "zdr", "zlr", "zrt", "ztl", "ztd", "zur", "zcs",
    };
    public static final String[] MOVE_UP = {
            "bud",
            "cud", "ctr", "ctl", "cul", "ctd", "cup", "cur", "ccs",
            "dud", "dtr", "dtl", "dul", "dtd", "dup", "dur", "dcs",
            "fud", "ftr", "ftl", "ful", "ftd", "fup", "fur", "fcs",
            "iud", "itr", "itl", "iul", "itd", "hup", "iur", "ics",
            "jup", "jtl", "jtr", "jru", "jlu", "jcl", "jcu", "jcr",
            "lud", "ltr", "ltl", "lul", "ltd", "lup", "lur", "lcs",
            "nud", "ntr", "ntl", "nul", "ntd", "nup", "nur", "ncs",
            "pud", "ptr", "ptl", "pul", "ptd", "pup", "pur", "pcs",
            "sud", "str", "stl", "sul", "std", "sup", "sur", "scs",
            "vud", "vtr", "vtl", "vul", "vtd", "vup", "vur", "vcs",
            "wud", "wtr", "wtl", "wul", "wtd", "wup", "wur", "wcs",
            "xud", "xtr", "xtl", "xul", "xtd", "xup", "xur", "xcs",
            "yud", "ytr", "ytl", "yul", "ytd", "yup", "yur", "ycs",
            "zud", "ztr", "ztl", "zul", "ztd", "zup", "zur", "zcs",
    };
    public static final String[] MOVE_FROM_UP = {
            "bud",
            "cud", "ctr", "ctl", "cul", "ctd", "cup", "cur", "ccs",
            "dud", "dtr", "dtl", "dul", "dtd", "dup", "dur", "dcs",
            "fud", "ftr", "ftl", "ful", "ftd", "fup", "fur", "fcs",
            "gud", "gtr", "gtl", "gul", "gtd", "gup", "gur", "gcs",
            "hud", "htr", "htl", "hul", "htd", "hup", "hur", "hcs",
            "iud", "itr", "itl", "iul", "itd", "hup", "iur", "ics",
            "jup", "jtl", "jtr", "jru", "jlu", "jcl", "jcu", "jcr",
            "lud", "ltr", "ltl", "lul", "ltd", "lup", "lur", "lcs",
            "mud", "mtr", "mtl", "mul", "mtd", "mup", "mur", "mcs",
            "nud", "ntr", "ntl", "nul", "ntd", "nup", "nur", "ncs",
            "pud", "ptr", "ptl", "pul", "ptd", "pup", "pur", "pcs",
            "qud", "qtr", "qtl", "qul", "qtd", "qup", "qur", "qcs",
            "sud", "str", "stl", "sul", "std", "sup", "sur", "scs",
            "tud", "ttr", "ttl", "tul", "ttd", "tup", "tur", "tcs",
            "vud", "vtr", "vtl", "vul", "vtd", "vup", "vur", "vcs",
            "wud", "wtr", "wtl", "wul", "wtd", "wup", "wur", "wcs",
            "xud", "xtr", "xtl", "xul", "xtd", "xup", "xur", "xcs",
            "yud", "ytr", "ytl", "yul", "ytd", "yup", "yur", "ycs",
            "zud", "ztr", "ztl", "zul", "ztd", "zup", "zur", "zcs",
    };
    public static final String[] MOVE_FROM_LEFT = {
            "blr",
            "cdl", "ctu", "clt", "clr", "ctr", "cul", "ctd", "ccs",
            "ddl", "dtu", "dlt", "dlr", "dtr", "dul", "dtd", "dcs",
            "fdl", "ftu", "flt", "flr", "ftr", "ful", "ftd", "fcs",
            "gdl", "gtu", "glt", "glr", "gtr", "gul", "gtd", "gcs",
            "hdl", "htu", "hlt", "hlr", "htr", "hul", "htd", "hcs",
            "idl", "itu", "ilt", "ilr", "itr", "iul", "itd", "ics",
            "jlt", "jtu", "jtd", "jdl", "jul", "jcd", "jcl", "jcu",
            "ldl", "ltu", "llt", "llr", "ltr", "lul", "ltd", "lcs",
            "mdl", "mtu", "mlt", "mlr", "mtr", "mul", "mtd", "mcs",
            "ndl", "ntu", "nlt", "nlr", "ntr", "nul", "ntd", "ncs",
            "pdl", "ptu", "plt", "plr", "ptr", "pul", "ptd", "pcs",
            "qdl", "qtu", "qlt", "qlr", "qtr", "qul", "qtd", "qcs",
            "sdl", "stu", "slt", "slr", "str", "sul", "std", "scs",
            "tdl", "ttu", "tlt", "tlr", "ttr", "tul", "ttd", "tcs",
            "vdl", "vtu", "vlt", "vlr", "vtr", "vul", "vtd", "vcs",
            "wdl", "wtu", "wlt", "wlr", "wtr", "wul", "wtd", "wcs",
            "xdl", "xtu", "xlt", "xlr", "xtr", "xul", "xtd", "xcs",
            "ydl", "ytu", "ylt", "ylr", "ytr", "yul", "ytd", "ycs",
            "zdl", "ztu", "zlt", "zlr", "ztr", "zul", "ztd", "zcs",
    };
    public static final String[] MOVE_FROM_RIGHT = {
            "blr",
            "ctu", "cdr", "clr", "crt", "ctl", "ctd", "cur", "ccs",
            "dtu", "ddr", "dlr", "drt", "dtl", "dtd", "dur", "dcs",
            "ftu", "fdr", "flr", "frt", "ftl", "ftd", "fur", "fcs",
            "gtu", "gdr", "glr", "grt", "gtl", "gtd", "gur", "gcs",
            "htu", "hdr", "hlr", "hrt", "htl", "htd", "hur", "hcs",
            "itu", "idr", "ilr", "irt", "itl", "itd", "iur", "ics",
            "jrt", "jtu", "jtd", "jdr", "jur", "jcd", "jcu", "jcr",
            "ltu", "ldr", "llr", "lrt", "ltl", "ltd", "lur", "lcs",
            "mtu", "mdr", "mlr", "mrt", "mtl", "mtd", "mur", "mcs",
            "ntu", "ndr", "nlr", "nrt", "ntl", "ntd", "nur", "ncs",
            "ptu", "pdr", "plr", "prt", "ptl", "ptd", "pur", "pcs",
            "qtu", "qdr", "qlr", "qrt", "qtl", "qtd", "qur", "qcs",
            "stu", "sdr", "slr", "srt", "stl", "std", "sur", "scs",
            "ttu", "tdr", "tlr", "trt", "ttl", "ttd", "tur", "tcs",
            "vtu", "vdr", "vlr", "vrt", "vtl", "vtd", "vur", "vcs",
            "wtu", "wdr", "wlr", "wrt", "wtl", "wtd", "wur", "wcs",
            "xtu", "xdr", "xlr", "xrt", "xtl", "xtd", "xur", "xcs",
            "ytu", "ydr", "ylr", "yrt", "ytl", "ytd", "yur", "ycs",
            "ztu", "zdr", "zlr", "zrt", "ztl", "ztd", "zur", "zcs",
    };
    public static final String[] MOVE_FROM_DOWN = {
            "bud",
            "cdn", "cdl", "ctu", "cdr", "cud", "ctr", "ctl", "ccs",
            "ddn", "ddl", "dtu", "ddr", "dud", "dtr", "dtl", "dcs",
            "fdn", "fdl", "ftu", "fdr", "fud", "ftr", "ftl", "fcs",
            "gdn", "gdl", "gtu", "gdr", "gud", "gtr", "gtl", "gcs",
            "hdn", "hdl", "htu", "hdr", "hud", "htr", "htl", "hcs",
            "idn", "idl", "itu", "idr", "iud", "itr", "itl", "ics",
            "jdn", "jtl", "jtr", "jrd", "jld", "jcd", "jcl", "jcr",
            "ldn", "ldl", "ltu", "ldr", "lud", "ltr", "ltl", "lcs",
            "mdn", "mdl", "mtu", "mdr", "mud", "mtr", "mtl", "mcs",
            "ndn", "ndl", "ntu", "ndr", "nud", "ntr", "ntl", "ncs",
            "pdn", "pdl", "ptu", "pdr", "pud", "ptr", "ptl", "pcs",
            "qdn", "qdl", "qtu", "qdr", "qud", "qtr", "qtl", "qcs",
            "sdn", "sdl", "stu", "sdr", "sud", "str", "stl", "scs",
            "tdn", "tdl", "ttu", "tdr", "tud", "ttr", "ttl", "tcs",
            "vdn", "vdl", "vtu", "vdr", "vud", "vtr", "vtl", "vcs",
            "wdn", "wdl", "wtu", "wdr", "wud", "wtr", "wtl", "wcs",
            "xdn", "xdl", "xtu", "xdr", "xud", "xtr", "xtl", "xcs",
            "ydn", "ydl", "ytu", "ydr", "yud", "ytr", "ytl", "ycs",
            "zdn", "zdl", "ztu", "zdr", "zud", "ztr", "ztl", "zcs",
    };
}
