package com.ollum.mazecape.Arrays;

public class Templates {
    public static final String[][] TEMPLATE_3x3 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"0", "0", "f", "100"},
            {},
            {}
    };
    public static final String[][] TEMPLATE_4x4 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"0", "0", "f", "100"},
            {},
            {}
    };
    public static final String[][] TEMPLATE_5x5 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"0", "0", "f", "100"},
            {},
            {}
    };
    public static final String[][] TEMPLATE_6x6 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"0", "0", "f", "100"},
            {},
            {}
    };
    public static final String[][] TEMPLATE_7x7 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"0", "0", "f", "100"},
            {},
            {}
    };
    public static final String[][] TEMPLATE_8x8 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"0", "0", "f", "100"},
            {},
            {}
    };
    public static final String[][] TEMPLATE_9x9 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"0", "0", "f", "100"},
            {},
            {}
    };
    public static final String[][] TEMPLATE_10x10 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"0", "0", "f", "100"},
            {},
            {}
    };
    public static final String[][] TEMPLATE_11x11 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"0", "0", "f", "100"},
            {},
            {}
    };
    public static final String[][] TEMPLATE_15x15 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"0", "0", "f", "100"},
            {},
            {}
    };
    public static final String[][] TEMPLATE_20x20 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"0", "0", "f", "100"},
            {},
            {}
    };
}
