package com.ollum.mazecape.Arrays;

public class World2 {
    public static final String[][] CAVE_01 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "c", "26"},
            {},
            {}
    };
    public static final String[][] CAVE_02 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndn", "srt", "nlr", "ntu", "nlt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "vud", "vdr", "vtu", "lcs", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "vur", "vul", "vup", "nud", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "ntd", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "glt", "frt", "sul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "c", "30"},
            {},
            {}
    };
    public static final String[][] CAVE_03 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ndl", "ndr", "nlr", "ntu", "ntu", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "srt", "nul", "nur", "ndl", "nur", "ntr", "sdn", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ndl", "ndr", "slt", "ntl", "ndl", "nur", "nul", "nud", "ndn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntd", "nul", "ndr", "ntr", "nur", "flt", "ndr", "ntd", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nlr", "nul", "nur", "nlt", "nrt", "ntd", "nlr", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "c", "57"},
            {},
            {}
    };
    public static final String[][] CAVE_04 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ntu", "ndl", "ndr", "ndl", "ndr", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "ttl", "nul", "nup", "nud", "sdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ndl", "nur", "ndl", "nrt", "ntr", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndn", "nud", "ndr", "nul", "sdn", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "ndl", "nud", "ttl", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nul", "sdn", "ntl", "nul", "ntl", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nul", "nur", "nlr", "nul", "nup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "6", "c", "51"},
            {},
            {"5,4", "8,7"}
    };
    public static final String[][] CAVE_05 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "ftu", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "ndl", "mud", "ndr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ndl", "sup", "nud", "wup", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "ndl", "ntl", "clr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "sdn", "nud", "nur", "nlr", "slt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "ttd", "nlr", "ndl", "ndr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nlr", "glt", "nur", "nul", "fup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"6", "3", "c", "100"},
            {},
            {"5,8"}
    };
    public static final String[][] CAVE_06 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ndl", "prt", "nlr", "wlr", "nlr", "sdl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndn", "ntl", "nlr", "nlr", "plt", "ndn", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "fud", "ntl", "nlt", "ndr", "tlr", "sul", "pup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nup", "prt", "ntd", "plt", "prt", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sud", "ndr", "ntu", "ndl", "prt", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "pur", "ctd", "mlr", "nlr", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "c", "37"},
            {"7,4", "9,5", "5,3", "8,6", "7,7", "7,6", "5,6", "5,8"},
            {"7,5"}
    };
    public static final String[][] CAVE_07 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ndl", "ndr", "nlr", "ndl", "sdn", "ndr", "ntu", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "sup", "nud", "ndr", "nul", "nud", "ntl", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ndl", "nud", "nur", "nlr", "ntr", "nur", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "ndr", "ndl", "nud", "ndr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "ntl", "ncs", "nul", "nud", "ndr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nul", "nur", "ntr", "ndr", "nul", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndn", "ndr", "ndl", "nud", "nud", "ndr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ncs", "nul", "nud", "nup", "nud", "nup", "grt", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ntd", "nlr", "ntd", "nlr", "ftd", "nlr", "nlr", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"7", "7", "c", "70"},
            {},
            {}
    };
    public static final String[][] CAVE_08 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sdn", "ndn", "wdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ccs", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ccs", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ccs", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "mud", "tud", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ccs", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ccs", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "gur", "nul", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"4", "3", "c", "20"},
            {},
            {"4,7"}
    };
    public static final String[][] CAVE_09 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nlr", "ntu", "nlr", "plt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "plt", "cud", "prt", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "ntd", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nlr", "ttu", "nlr", "plt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "prt", "ndl", "ntl", "nlr", "plt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "wrt", "nul", "nur", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "prt", "nlr", "mtu", "nlt", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "plt", "pup", "prt", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odl", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "c", "49"},
            {"7,3", "4,10", "4,4", "3,7", "6,4", "7,7", "7,6", "3,9", "5,10", "6,10"},
            {"5,6"}
    };
    public static final String[][] CAVE_10 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nlr", "mtu", "ntu", "nlr", "nlt", "pdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "wdn", "gdn", "nud", "nud", "ndr", "slt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nul", "tud", "nur", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlr", "tlr", "ncs", "tlr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlr", "ndl", "tud", "ndr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "srt", "nul", "nud", "nud", "sup", "nup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "pup", "nrt", "nlr", "ntd", "ntd", "nlr", "nlt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"6", "6", "c", "56"},
            {"3,9", "9,3"},
            {"6,5", "5,6", "7,6", "6,7"}
    };
    public static final String[][] CAVE_11 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntu", "nlr", "nlr", "nlt", "ndr", "nlr", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nup", "nud", "ndr", "ndl", "ndr", "ntd", "flt", "ndr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntr", "nud", "nur", "nul", "ndr", "ntu", "nul", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nup", "nur", "ndl", "ndr", "ntr", "nup", "ndr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ndl", "ndr", "nul", "nud", "fup", "ndr", "nul", "sdn", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "ndl", "nur", "nlr", "ntd", "nlr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "nud", "ndr", "nul", "ndr", "nlr", "ndl", "ndr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "nur", "ndl", "nud", "srt", "nul", "ntl", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlr", "ndl", "nud", "nud", "ndr", "ndl", "nur", "flt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "flt", "nur", "ntd", "nul", "gup", "nur", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"7", "3", "c", "114"},
            {},
            {}
    };
    public static final String[][] CAVE_12 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nlr", "nlr", "nlr", "ntu", "ndl", "ndn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "nlr", "nul", "nur", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlr", "ndl", "srt", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "mtl", "ntd", "nlt", "ntl", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ndl", "nur", "nlt", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "nlr", "nlr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "nur", "nlr", "glt", "wrt", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"7", "3", "c", "100"},
            {},
            {}
    };
    public static final String[][] CAVE_13 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "nlr", "slt", "ndr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ndl", "ndr", "nlr", "nlr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nup", "nud", "nur", "ndl", "srt", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ttd", "slt", "nur", "ndl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ndl", "ndr", "nul", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "ntd", "nlr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntd", "nlt", "grt", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"4", "9", "c", "100"},
            {},
            {"4,6"}
    };
    public static final String[][] CAVE_14 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ntu", "nlr", "nlr", "ntu", "nlr", "nlr", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "fdn", "nur", "nlr", "nlt", "nud", "nrt", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlr", "nlr", "nlr", "ttd", "nlr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlr", "nlr", "nlr", "ndl", "ndr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "sdn", "ndr", "nlr", "nul", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "nud", "srt", "nlr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "nur", "nlr", "nlr", "ndl", "fup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntd", "ntd", "nlr", "nlr", "nlt", "nur", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "c", "100"},
            {},
            {"7,5"}
    };
    public static final String[][] CAVE_15 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ndl", "ndn", "ndr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "ttd", "nul", "cud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "srt", "ndl", "ndr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "gdn", "nur", "ntr", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "nur", "clr", "nul", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"5", "3", "c", "100"},
            {},
            {"5,4"}
    };
    public static final String[][] CAVE_16 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sdn", "ndn", "ndr", "nlr", "nlr", "nlr", "nlr", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "ndr", "nlr", "ntu", "nlr", "wlt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ntl", "ntr", "nud", "ndr", "mtd", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "ful", "fur", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "fdl", "fdr", "ndl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "mtu", "nul", "nud", "mtl", "ntr", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "wrt", "nlr", "ntd", "nlr", "nul", "nud", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nlr", "nlr", "nlr", "nlr", "nul", "wup", "gup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"4", "3", "c", "100"},
            {},
            {}
    };
    public static final String[][] CAVE_17 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nlr", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ndl", "ndr", "ttr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nrt", "ttd", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ttl", "ndl", "srt", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nrt", "ttd", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "nur", "glt", "frt", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"5", "3", "c", "100"},
            {},
            {"7,4", "5,5", "3,6", "6,9"}
    };
    public static final String[][] CAVE_18 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndn", "wrt", "nlr", "ndl", "ndr", "ndl", "wdn", "sdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlr", "ntr", "nud", "nud", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntd", "ndl", "nup", "fup", "ntl", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nlr", "ntd", "mlr", "nlr", "ntd", "nlr", "mtr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ttu", "nlr", "nlr", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sur", "nlt", "ntl", "ndl", "ndr", "ndl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ndl", "nup", "nud", "nup", "nur", "ttd", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "nul", "frt", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "pup", "pdn", "prt", "ndl", "pdn", "prt", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "pdn", "nud", "nrt", "ntd", "nul", "prt", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nul", "ndr", "ndl", "prt", "nlr", "ndl", "fdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "plt", "pup", "nur", "plt", "srt", "ntd", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ntu", "ndl", "nrt", "ntu", "ntu", "clr", "plt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "wrt", "nul", "nur", "nlr", "nul", "ntl", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ntu", "nlr", "ntu", "nlr", "nul", "nrt", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "prt", "mtd", "nlt", "nur", "nlr", "flt", "prt", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "6", "c", "100"},
            {"3,11", "3,12", "4,11", "5,11", "7,11", "8,11", "8,12", "10,15", "4,14", "5,14", "7,14", "7,13", "3,18", "9,18"},
            {"5,7", "9,9"}
    };
    public static final String[][] CAVE_19 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "prt", "nlr", "ndl", "ndr", "ntu", "nlr", "nlr", "ndl", "fdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nul", "nud", "nud", "ndr", "ndl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "slt", "nud", "pup", "nud", "wup", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "nul", "pdn", "nur", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlr", "plt", "prt", "ncs", "plt", "prt", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nlr", "ndl", "pup", "ndr", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ndl", "sdn", "nud", "pdn", "nud", "srt", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "nul", "nud", "nud", "ndr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "gup", "nur", "nlr", "nlr", "mtd", "nul", "nur", "nlr", "plt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"7", "7", "c", "100"},
            {"3,3", "11,11", "7,6", "7,9", "7,8", "7,5", "6,7", "9,7", "8,7", "5,7"},
            {}
    };
    public static final String[][] CAVE_20 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "otu", "oup", "oup", "oup", "otu", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntu", "plt", "rud", "wdn", "prt", "plt", "rud", "ndr", "ntu", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "fcs", "ndl", "rud", "nur", "nlr", "ndl", "rud", "nud", "pup", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "pup", "nur", "pul", "rud", "prt", "plt", "pup", "rud", "pup", "srt", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "otl", "rlr", "rlr", "rlr", "rcs", "rlr", "rlr", "rlr", "rcs", "rlr", "rlr", "rlr", "otr", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "pdn", "prt", "ndl", "rud", "ndr", "nlr", "slt", "rud", "ndr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "prt", "nul", "rud", "pud", "grt", "plt", "rud", "mud", "prt", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "slt", "rud", "nur", "nlr", "plt", "rud", "nur", "nlr", "plt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "otl", "rlr", "rlr", "rlr", "rcs", "rlr", "rlr", "rlr", "rcs", "rlr", "rlr", "rlr", "otr", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "pdn", "ndr", "ndl", "rud", "ndr", "plt", "pdn", "rud", "ndr", "ndl", "pdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "pcs", "ntr", "rud", "nud", "pdn", "tud", "rud", "nur", "pcs", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "pup", "nur", "nul", "rud", "nur", "nul", "pup", "rud", "prt", "ntd", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "otd", "odn", "odn", "odn", "otd", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "c", "100"},
            {"5,3", "12,4", "3,5", "4,12", "5,5", "12,12", "9,8", "12,8", "13,9", "13,11", "11,13", "9,13", "9,11", "8,11", "8,12", "7,5", "8,5", "8,3", "9,3", "9,9", "7,8", "4,8", "4,7", "3,13", "3,11", "3,7", "9,5", "11,5"},
            {"9,12"}
    };
    public static final String[][] CAVE_21 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "wdn", "ndr", "nlr", "nlr", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "ndl", "frt", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ncs", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "nud", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "mud", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ncs", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "wdn", "nud", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "fup", "ntl", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ntl", "nlt", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "ndr", "nul", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "mud", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ncs", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ntd", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "gdn", "nup", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "fup", "nur", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "slt", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "our", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"5", "5", "c", "100"},
            {},
            {}
    };
    public static final String[][] CAVE_22 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "wdr", "ctu", "cdl", "sdn", "cdr", "ctu", "wdl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ctl", "ccs", "ccs", "mcs", "ccs", "ccs", "ctr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "cur", "ccs", "ccs", "ccs", "ccs", "ccs", "cul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "mcs", "ccs", "fcs", "ccs", "mcs", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "cdr", "ccs", "ccs", "ccs", "ccs", "ccs", "cdl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ctl", "ccs", "ccs", "mcs", "ccs", "ccs", "ctr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "wur", "ctd", "cul", "gup", "cur", "ctd", "wul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"6", "6", "c", "100"},
            {},
            {}
    };
    public static final String[][] CAVE_23 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "fdn", "ndr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "ndr", "nlr", "mtu", "nlr", "nlr", "flt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "gup", "sdn", "nud", "ndr", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "nul", "nud", "nur", "nlr", "ntu", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nlr", "nlr", "ncs", "nlr", "ndl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "ndl", "nud", "ndr", "nul", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ndl", "nud", "nud", "nud", "wrt", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "sup", "nud", "nud", "nud", "nur", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nul", "nur", "ntd", "nlr", "nlr", "nlr", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"7", "7", "c", "132"},
            {},
            {}
    };
    public static final String[][] CAVE_24 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ntu", "nlr", "nlr", "ndl", "ndr", "nlr", "nlr", "ntu", "nlr", "ntu", "nlt", "ndr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nrt", "ntd", "nlt", "ndn", "nur", "ncs", "nlr", "ntu", "ntd", "nlt", "nup", "ndr", "ntr", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntu", "nlr", "nlt", "nud", "nrt", "ntr", "nrt", "ntr", "ndr", "nlr", "ndl", "nud", "nup", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ntd", "ntu", "nlr", "ncs", "nlt", "ntl", "nlt", "nup", "nud", "nrt", "ntd", "ntr", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nul", "nrt", "nul", "ndr", "nul", "ndn", "ndr", "ntd", "nlt", "ndr", "ncs", "ntr", "ndn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nup", "ndr", "nlr", "nlr", "ntu", "nul", "ndr", "nul", "nud", "ndr", "nlr", "ntr", "nud", "nur", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntr", "nrt", "ndl", "nur", "ntu", "nul", "ndr", "ntr", "nup", "ndr", "nul", "nud", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ntl", "nlr", "nul", "nrt", "nul", "ndr", "nul", "nup", "ndr", "ntr", "ndr", "nul", "ntl", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ntl", "nlr", "ntu", "nlr", "ntu", "nul", "ndr", "ndl", "nup", "ntl", "nul", "ndr", "ntr", "nup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntd", "ndl", "nud", "ndn", "nud", "nrt", "ntr", "nur", "slt", "ntl", "ndl", "nud", "nud", "ndn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ntr", "ntl", "ntr", "ntl", "nlt", "ntl", "nlt", "ndr", "nul", "nud", "nud", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ntd", "nul", "nur", "ntr", "ndr", "nul", "ndn", "nud", "ndn", "nud", "nur", "nlr", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "ndr", "ntu", "ndl", "nur", "ntr", "ndr", "ntr", "nur", "ntd", "ncs", "nlr", "ndl", "sdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntd", "nul", "nud", "nur", "ndl", "nur", "ntr", "nur", "ndl", "ndn", "nud", "ndr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nlr", "nul", "nrt", "ntd", "slt", "nur", "nlr", "nul", "nur", "ntd", "ntd", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "8", "c", "147"},
            {},
            {}
    };
    public static final String[][] CAVE_25 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntu", "nlt", "ndr", "nlr", "nlr", "nlr", "nlr", "ndl", "nrt", "nlr", "ndl", "ndr", "nlr", "nlr", "nlr", "ntu", "nlr", "nlr", "flt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nup", "ndr", "nul", "ndr", "ntu", "nlr", "ndl", "ntl", "nlr", "ndl", "nud", "nur", "nlr", "ndl", "ndn", "nur", "ndl", "ndr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nul", "nrt", "nul", "nur", "ndl", "nud", "nur", "ndl", "nup", "nur", "ndl", "ndn", "nur", "ntr", "ndn", "nur", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "nlr", "nlr", "nlr", "nul", "nud", "ndr", "ntr", "ndr", "nlr", "nul", "ntl", "nlt", "nur", "ntd", "ndl", "ndn", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlr", "nlr", "ntu", "nlr", "flt", "nud", "nud", "nup", "nur", "nlr", "ndl", "nur", "nlr", "ntu", "nlr", "ntd", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "ndl", "nur", "nlr", "nlr", "nul", "nud", "ndr", "nlr", "ndl", "nur", "nlr", "ndl", "nud", "ndn", "ndr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntu", "ndl", "nur", "nlr", "nlr", "ndl", "fdn", "nud", "ntl", "flt", "nur", "nlr", "ndl", "nud", "nur", "ntr", "nur", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nup", "ndr", "nlr", "nlr", "nul", "nud", "nur", "nul", "ndr", "nlr", "ndl", "nud", "nud", "nrt", "ntd", "nlr", "slt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "nul", "ndr", "nlr", "nlr", "ntr", "ndr", "nlr", "nul", "sdn", "nur", "ntr", "nur", "nlr", "nlr", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ndl", "ndr", "nul", "nrt", "ndl", "nud", "nur", "nlr", "ndl", "nur", "ndl", "nur", "nlr", "nlr", "nlr", "ndl", "nur", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nup", "ntl", "nul", "nrt", "ntu", "ntr", "nur", "ntu", "ndl", "nur", "ndl", "ntl", "ndl", "ndr", "nlr", "ndl", "nud", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ndl", "nur", "nlr", "nlr", "nul", "nur", "ndl", "nud", "nur", "ndl", "nud", "nup", "nur", "ntd", "ndl", "nur", "nul", "nud", "fdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndn", "nud", "ndr", "ndl", "ndr", "ndl", "srt", "nul", "nud", "ndr", "nul", "nur", "nlr", "nlr", "ndl", "nur", "nlr", "ndl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nul", "nur", "nul", "nud", "ndr", "nlr", "nul", "nud", "ndr", "nlt", "ndr", "nlr", "nul", "frt", "ndl", "nud", "nur", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntu", "nlr", "flt", "ndr", "nul", "nud", "ndr", "ndl", "ntl", "nul", "ndr", "nul", "nrt", "ntu", "ndl", "nud", "nud", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "ndl", "ndr", "nul", "ndr", "nul", "nud", "nur", "nul", "ndr", "nul", "nrt", "ntu", "nul", "nur", "nul", "nud", "nud", "ndn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ndl", "nud", "nud", "ndr", "ntd", "ndl", "nud", "fdn", "ndr", "nul", "ndr", "ndl", "nur", "ndl", "ndr", "ndl", "nud", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "nur", "nul", "nud", "ndr", "nul", "nur", "ntr", "nur", "nlr", "nul", "nur", "ndl", "nur", "nul", "nur", "nul", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlr", "ndl", "nup", "nud", "ndr", "nlt", "nud", "nrt", "ntu", "ndl", "ndr", "nul", "ndr", "nlr", "nlr", "ndl", "nur", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "nrt", "ntd", "nlr", "nul", "nur", "nlr", "ntd", "nlr", "nul", "gup", "nur", "nlr", "ntd", "nlr", "flt", "nur", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"12", "3", "c", "400"},
            {},
            {}
    };
}
