package com.ollum.mazecape.Arrays;

public class World4 {
    public static final String[][] DESERT_01 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntu", "nlr", "nlr", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "sdn", "ndr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "sdn", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "gup", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"4", "3", "d", "39"},
            {},
            {},
            {}
    };
    public static final String[][] DESERT_02 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ndl", "srt", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nul", "nur", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ndl", "ndr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nul", "gup", "srt", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"5", "3", "d", "34"},
            {},
            {},
            {}
    };
    public static final String[][] DESERT_03 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sdn", "ndr", "ntu", "nlt", "ndr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "nud", "ndr", "nul", "sdn", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nul", "nud", "ndr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ndl", "nur", "ntr", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "nlr", "nul", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "ndr", "nlr", "ndl", "ndr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "nur", "glt", "nur", "nul", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"5", "3", "d", "55"},
            {},
            {},
            {}
    };
    public static final String[][] DESERT_04 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nlr", "ntu", "nlr", "nlr", "nlr", "nlt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ncs", "nlr", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlt", "nur", "nlr", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ndl", "ndr", "nlr", "nlr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nul", "nur", "nlr", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "grt", "nlr", "nlr", "nlr", "mtu", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nlr", "nlr", "nlr", "nul", "wrt", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"9", "3", "d", "71"},
            {},
            {},
            {}
    };
    public static final String[][] DESERT_05 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nlr", "nlr", "ntu", "tlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "tlr", "ntd", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "ndr", "nlr", "ndl", "cud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sdn", "nud", "grt", "nul", "ntl", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntd", "slt", "ndr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "tlr", "ntd", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "d", "33"},
            {},
            {"7,3", "5,4", "5,8"},
            {}
    };
    public static final String[][] DESERT_06 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nlr", "mtu", "ndl", "ndr", "nlr", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nul", "gup", "ntl", "ntu", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ntu", "ntu", "ncs", "ntr", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "ntd", "ntd", "ntd", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntu", "ntu", "ntu", "ntu", "ntu", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntd", "nul", "nud", "nur", "ntd", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "wlt", "nup", "srt", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"6", "6", "d", "48"},
            {},
            {},
            {}
    };
    public static final String[][] DESERT_07 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndn", "ndr", "ndl", "ndr", "nlr", "ndl", "ndr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "nud", "gdn", "nud", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "nud", "nud", "sup", "nup", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "nur", "ntd", "ylr", "cdl", "ndr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "ndl", "ndr", "ndl", "nud", "nud", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "pdn", "nud", "nud", "ntl", "ntd", "nul", "nud", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "zup", "nur", "nul", "nur", "nlr", "nlr", "ntd", "plt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "d", "100"},
            {"10,9", "3,8"},
            {},
            {"3,9", "7,6"}
    };
    public static final String[][] DESERT_08 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "ndl", "ndr", "ntu", "ndl", "ndr", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "prt", "ntr", "ntl", "mcs", "ntr", "ntl", "plt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "pup", "gup", "pup", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ndl", "ndr", "nlr", "ntu", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nul", "nud", "wup", "xxx", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ndl", "nud", "sdn", "ndr", "nul", "nup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "prt", "nul", "nur", "nul", "nur", "nlr", "plt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"6", "3", "d", "56"},
            {"5,5", "3,9", "7,5", "9,9", "3,4", "9,4"},
            {},
            {}
    };
    public static final String[][] DESERT_09 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nlr", "nlr", "ndl", "fdn", "ndr", "nlr", "ndl", "sdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "nul", "tud", "nur", "ndl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ydl", "nlr", "ncs", "nlr", "ydl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "nud", "xxx", "nud", "xxx", "nud", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nlr", "ncs", "nlr", "zcs", "nlr", "ncs", "mlr", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ndl", "nud", "xxx", "nud", "xxx", "nud", "ndr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "ydl", "nlr", "ncs", "nlr", "ydl", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "ndl", "tud", "ndr", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "wup", "nur", "nlr", "nul", "fup", "nur", "nlr", "nlr", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "7", "d", "100"},
            {},
            {"7,4", "7,10"},
            {"7,7", "5,5", "7,7", "9,5", "7,7", "5,9", "7,7", "9,9"}
    };
    public static final String[][] DESERT_10 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ndl", "ndr", "nlr", "ndl", "ndr", "ndl", "ndr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "nud", "ndr", "nul", "nud", "nur", "nul", "nrt", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nul", "nur", "ntu", "ntr", "sdn", "ndr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "slt", "ndr", "nul", "fup", "nur", "nul", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ntu", "nul", "ndr", "nlr", "ndl", "fdn", "nud", "gup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nul", "nur", "ndl", "ntl", "ndl", "nur", "nul", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlr", "flt", "nud", "nud", "nur", "nlr", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ndl", "nur", "ncs", "nlr", "nlt", "ndr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "ndl", "nud", "ndr", "ndl", "nur", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "srt", "nul", "nur", "nul", "nur", "nlr", "nlr", "nlt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"12", "12", "d", "129"},
            {},
            {},
            {}
    };
    public static final String[][] DESERT_11 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ntu", "ndl", "ndr", "nlr", "ntu", "ntu", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ndl", "nup", "nur", "nul", "nrt", "nul", "ntl", "nlt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntd", "flt", "ndn", "srt", "ndl", "nrt", "nul", "ndr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntu", "nlt", "nur", "ndl", "nud", "ndr", "nlt", "nud", "nup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "ndl", "nud", "nur", "ntd", "ndl", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "srt", "nlr", "nul", "nud", "ndr", "nlr", "ntr", "fdn", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "ndl", "ndr", "nul", "nud", "ndn", "nur", "ntr", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntu", "ntd", "nul", "ndr", "nul", "ntl", "ndl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nup", "ntl", "ndl", "ndn", "nud", "srt", "ntr", "ntl", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nul", "nur", "nul", "nur", "glt", "nup", "nur", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"6", "5", "d", "93"},
            {},
            {},
            {}
    };
}
