package com.ollum.mazecape.Arrays;

public class World1 {
    public static final String[][] FOREST_01 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "slr", "slr", "slr", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "f", "4"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_02 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sdr", "nlr", "sdl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "sdl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nul", "gup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "5", "f", "8"},
            {"4,5", "3,7"},
            {"5,4"},
            {"3,4"}
    };
    public static final String[][] FOREST_03 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sdn", "ndr", "ntu", "dlt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nul", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntu", "slt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nul", "grt", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"4", "3", "f", "22"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_04 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ntu", "ndl", "sdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "sdn", "nud", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntr", "nur", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sdn", "nud", "ndr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "gup", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"5", "3", "f", "38"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_05 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sdr", "nlr", "sdl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "mdl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "gup", "wup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"4", "3", "f", "12"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_06 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "drt", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "glt", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"5", "3", "f", "34"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_07 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "otu", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "gdn", "rud", "sdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "pup", "rud", "wud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "otl", "rlr", "rtr", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "pdn", "rud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sud", "rup", "sud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "mur", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"5", "8", "f", "15"},
            {"3,4", "3,6"},
            {},
            {}
    };
    public static final String[][] FOREST_08 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "otu", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "gdn", "ndr", "wlt", "rud", "sdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "mud", "nud", "rdr", "rul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntd", "blr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "rdr", "rul", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "rud", "srt", "ntd", "nlt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "otd", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"7", "7", "f", "26"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_09 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nlr", "nlr", "ntu", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ddl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "prt", "ntd", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "mtl", "ndl", "prt", "ndl", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "nur", "glt", "nur", "wlt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"5", "3", "f", "34"},
            {"4,5", "5,6"},
            {},
            {}
    };
    public static final String[][] FOREST_10 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ntu", "nlr", "nlr", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sdn", "nud", "ndr", "nlr", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nup", "ntl", "nlr", "flt", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ndl", "nud", "grt", "ndl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nul", "sdn", "nur", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "ndl", "nur", "nlr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nlr", "ntd", "nlr", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "f", "52"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_11 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "ndl", "ndr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ndl", "nud", "sup", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "mtl", "nul", "nud", "nur", "nlr", "ntd", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "sdn", "nur", "nlr", "ndl", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ntl", "ndl", "ndr", "nul", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "nud", "nud", "ndr", "wlt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nlr", "nul", "gup", "nur", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"6", "3", "f", "80"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_12 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndn", "ndr", "ntu", "nlr", "nlr", "nlr", "dlt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nul", "nur", "nlr", "nlt", "ndr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ctu", "nlt", "ndr", "ntr", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nul", "nur", "nlr", "ntr", "nud", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nlr", "ndl", "nud", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ndl", "ndr", "nul", "nur", "slt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "nur", "nul", "grt", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"6", "3", "f", "58"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_13 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "prt", "nlr", "wlt", "ndn", "nrt", "ntu", "plt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "ndl", "prt", "ntd", "plt", "ntl", "nlt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "prt", "ntd", "ntu", "mtu", "ntu", "ntd", "plt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "frt", "ntu", "nul", "nud", "nur", "ntu", "flt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "prt", "ntd", "slt", "gup", "srt", "ntd", "plt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"6", "3", "f", "33"},
            {"5,4", "3,7", "7,4", "9,7", "3,3", "9,5", "3,5", "9,3"},
            {},
            {}
    };
    public static final String[][] FOREST_14 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nlr", "ntu", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ndl", "cud", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "ntd", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntu", "ndl", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "cud", "fdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ntd", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "clr", "ndl", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "xxx", "nur", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "f", "30"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_15 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "nlr", "ntu", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nul", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlr", "ndl", "nud", "ndn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlt", "nud", "nur", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nul", "srt", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "ndr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nul", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ndl", "ndn", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sdn", "ntl", "ntd", "dlt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "grt", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"5", "3", "f", "65"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_16 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ntu", "nlr", "ndl", "wdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "nrt", "ntd", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "ndr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntd", "mtu", "flt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "slt", "nud", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nul", "ntl", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlt", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlr", "nul", "nup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntd", "ntu", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ndl", "nur", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "srt", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "frt", "nlr", "ntd", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlr", "nlr", "ntu", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "frt", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "ndl", "nup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "slt", "nur", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "f", "103"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_17 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "ntu", "ntu", "ndl", "sdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "ndr", "ndl", "nup", "nud", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "nur", "ndl", "ntl", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "ndl", "nud", "nup", "ndr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nul", "nur", "nlr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ndl", "nrt", "ntu", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "nur", "glt", "nur", "nlr", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"7", "6", "f", "64"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_18 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ndl", "ndr", "nlr", "nlr", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nrt", "ntr", "nup", "ndr", "ndl", "ndr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ndl", "nur", "nlr", "nul", "nud", "nud", "nur", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nrt", "ntu", "nlt", "nud", "nur", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "nur", "ndl", "ntl", "nlr", "ntd", "ntu", "nul", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nul", "nud", "ndr", "ndl", "nup", "ndr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ddn", "ndr", "nul", "nud", "nur", "nlr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nul", "ndr", "ntd", "nlr", "slt", "ndr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nlr", "nul", "grt", "nlr", "nlr", "nul", "nup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"6", "4", "f", "72"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_19 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nlr", "ntu", "nlt", "nrt", "nlr", "ntu", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndn", "ndr", "ntd", "nlr", "nlr", "nlr", "ntd", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntr", "ndr", "nlr", "ntu", "nlr", "nlt", "ntl", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nup", "nud", "ndr", "ntd", "ndl", "ndn", "nud", "nup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "ndr", "ntr", "nud", "gdn", "nud", "ntl", "nul", "sdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndn", "nud", "nup", "sup", "nur", "nul", "nud", "ndn", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntr", "frt", "nlr", "ntu", "nlr", "nul", "ntl", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "ntu", "nlr", "ntd", "nlr", "ntu", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "ntd", "nlr", "nlt", "nrt", "ntd", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "f", "64"},
            {},
            {},
            {}
    };

    public static final String[][] FOREST_20 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "nlr", "ndl", "wrt", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nlr", "slt", "ntl", "nlr", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ndl", "ndr", "ndl", "nud", "ndr", "nlr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nul", "pup", "nud", "nur", "plt", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "mtu", "nlr", "ncs", "nlr", "nlr", "ntd", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nul", "gdn", "nud", "ndr", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "sdn", "ndr", "nul", "nud", "nud", "sdn", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "ndl", "nud", "nud", "nud", "wup", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "mtd", "nlr", "nul", "nur", "nul", "nur", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"7", "7", "f", "112"},
            {"6,6", "9,6"},
            {},
            {}
    };
    public static final String[][] FOREST_21 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ntu", "ndl", "ndr", "ndl", "ndr", "ntu", "nlr", "nlr", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "nur", "nul", "nud", "nud", "nud", "ndr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "cdl", "ndr", "nlr", "nul", "nud", "nur", "ntd", "nlt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "ndr", "nlr", "ntd", "nlt", "ndr", "nlr", "mtr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "wup", "nud", "ndn", "ndr", "ndl", "nur", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "nud", "ndr", "ntd", "nul", "nud", "nur", "ndl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "nud", "fdn", "ndr", "nul", "frt", "ntd", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ndl", "nur", "ntr", "nur", "nlr", "nlr", "nlr", "ndl", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "dlt", "nur", "mtu", "nlr", "nlr", "wlt", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nlr", "nlr", "nul", "grt", "nlr", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "f", "115"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_22 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "ntu", "nlr", "nlt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nrt", "ntu", "ndl", "ndr", "nlr", "nlr", "ntr", "ndr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nul", "wup", "nud", "ndr", "nlr", "nul", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "ndl", "nud", "nur", "nlr", "slt", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "mtl", "nlr", "ndl", "nud", "nud", "ndr", "nlr", "nlr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ndl", "nud", "nud", "nur", "ntd", "ndl", "frt", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "nud", "nur", "nlr", "ndl", "nur", "nlr", "ntr", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "sdn", "nur", "ndl", "frt", "ntd", "nlr", "ndl", "nup", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "ndr", "nul", "ndr", "ndl", "sdn", "nur", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "nur", "nlr", "nul", "gup", "nur", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"12", "3", "f", "125"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_23 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "slt", "ndr", "nlr", "nlr", "ndl", "sdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlr", "ndl", "ndr", "ntd", "nlr", "ndl", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ndl", "nup", "nur", "nlr", "ndl", "ntl", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndn", "nud", "ndr", "nlr", "nlr", "mtr", "nup", "nrt", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntd", "ntr", "nrt", "nlr", "ntd", "nlr", "nlt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndn", "ndr", "ntd", "nlr", "nlr", "ntu", "flt", "sdn", "wup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntd", "nlr", "nlt", "ndn", "nud", "ndn", "nud", "ndn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlr", "nlr", "ntd", "mtr", "nud", "nur", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "wup", "nur", "nlr", "nlr", "glt", "nur", "ntd", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"7", "4", "f", "97"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_24 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nlr", "ntu", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "nud", "drt", "mlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ntd", "clr", "ndl", "tud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nrt", "ntu", "slt", "nur", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "wup", "ndr", "mtd", "nlr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "pdn", "nud", "fdn", "wrt", "ndr", "tud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "pup", "nur", "ndl", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlr", "tlr", "ncs", "clr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlr", "ntr", "sdn", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "gup", "nrt", "ntd", "ntd", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "f", "100"},
            {"4,9", "3,8"},
            {"8,5", "8,8", "5,10"},
            {}
    };
    public static final String[][] FOREST_25 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ntu", "ndl", "nrt", "nlr", "nlr", "ndl", "ndr", "ntu", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntr", "nur", "nlr", "nlr", "ndl", "nud", "nud", "nud", "nup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nup", "ndr", "nlr", "ndl", "ntl", "nul", "nud", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nul", "ndr", "nul", "nud", "ndr", "ntd", "flt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "nul", "srt", "nul", "nud", "ndr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlr", "nlr", "ndl", "ndr", "nlr", "nul", "nur", "ndl", "nup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "fdn", "ndr", "nul", "nud", "srt", "nlr", "ndl", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntr", "nur", "nlr", "ntd", "nlr", "nlr", "nul", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndn", "nud", "ndr", "ndl", "sdn", "ndr", "nlr", "ndl", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntd", "nul", "nur", "nul", "gup", "nrt", "ntd", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"6", "3", "f", "109"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_26 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ntu", "ndl", "ndr", "ntu", "ndl", "ndn", "ndr", "nlt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "nur", "ntr", "nud", "nur", "ntd", "ncs", "nlt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ndl", "ndr", "ntr", "nud", "ndn", "ndr", "nul", "ndn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ntl", "nul", "nur", "ncs", "ntr", "nur", "ntu", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ncs", "ntu", "nlt", "nud", "nur", "nlt", "nur", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "nud", "ndn", "nur", "ntu", "flt", "ndr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlr", "ntd", "ntr", "ndn", "nud", "ndr", "ntd", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "slt", "nud", "nud", "nur", "ncs", "nlt", "sup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nup", "nur", "nlr", "ntd", "ntd", "nlt", "nur", "nlr", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "f", "74"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_27 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntu", "nlr", "ndl", "ndr", "ndl", "ndr", "ntu", "nlr", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nup", "nur", "ndl", "nud", "nud", "nup", "nud", "nur", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nul", "nud", "nur", "ndl", "nud", "ndr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "srt", "nlr", "ntr", "ndr", "nul", "nud", "nur", "ndl", "nup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlr", "ndl", "nud", "nud", "ndr", "ntd", "flt", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndn", "nud", "nud", "nud", "nur", "ndl", "ndr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "ntl", "nul", "ndr", "nul", "nud", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "nup", "ndr", "nul", "ndr", "nul", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntr", "nur", "nlr", "nul", "ndr", "nul", "ndn", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "frt", "ntd", "nlr", "nlr", "slt", "gup", "nrt", "ntd", "ntd", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"8", "4", "f", "100"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_28 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndn", "ndr", "nlr", "nlr", "wlt", "ndn", "wrt", "nlr", "nlr", "ndl", "sdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "ndr", "nlr", "ndl", "nud", "ndr", "nlr", "ndl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "ndl", "nud", "nud", "nud", "ndr", "nul", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "nul", "ntl", "ntr", "nud", "nur", "nlr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nlr", "nlr", "nul", "nud", "nur", "mtu", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nlr", "nlr", "ntu", "nlr", "fcs", "nlr", "ntd", "nlr", "nlr", "nlt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "mtd", "ndl", "nud", "ndr", "nlr", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlr", "ndl", "nud", "ntl", "mtr", "ndr", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "ndr", "nul", "nud", "nud", "nud", "nur", "ndl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "nlr", "nul", "nud", "nur", "nlr", "nul", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "nur", "nlr", "nlr", "wlt", "nup", "srt", "nlr", "nlr", "nul", "gup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "f", "100"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_29 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ntu", "ndl", "nrt", "ntu", "nlr", "nlr", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ndl", "nud", "nur", "nlr", "ntr", "ndr", "nlr", "nlr", "ndl", "nup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "nur", "nlr", "ndl", "nud", "nur", "ntu", "nlt", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "slt", "ndr", "nlr", "nul", "nup", "ndr", "nul", "ndr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nup", "ndr", "nul", "ndr", "nlr", "nlr", "nul", "ndr", "nul", "ndn", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "ndr", "ntd", "nlr", "flt", "ndr", "nul", "srt", "ntd", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "nlr", "nul", "ndr", "nlr", "ndl", "nur", "nlr", "ntu", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlt", "nur", "ndl", "nur", "nlr", "ndl", "nup", "ndr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "ntu", "ndl", "nud", "ndr", "flt", "nud", "ndr", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nul", "nud", "nud", "nur", "ntu", "nul", "nud", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nlr", "nlr", "nul", "nur", "glt", "nur", "nlr", "nul", "nur", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"13", "4", "f", "100"},
            {},
            {},
            {}
    };
    public static final String[][] FOREST_30 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ntu", "nlr", "nlr", "nlr", "ntu", "nlr", "nlr", "nlr", "ndl", "ndr", "ntu", "nlr", "nlr", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "ndr", "ndl", "ndn", "nud", "ndr", "nlr", "ndl", "nup", "nud", "nur", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nul", "nud", "nur", "nul", "nud", "ndn", "nur", "nlr", "nul", "ndr", "ndl", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ndl", "nud", "ndr", "nlr", "nul", "ntl", "nlr", "nlr", "nlr", "nul", "nud", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ndl", "nur", "nul", "nur", "nlr", "ndl", "nur", "ndl", "ndr", "nlr", "ndl", "ntl", "nlt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "ntu", "nlr", "ndl", "nud", "ndr", "nul", "nud", "ndr", "nul", "nud", "ndr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlr", "ntr", "nrt", "nul", "nud", "nur", "ndl", "nud", "nud", "ndr", "nul", "nud", "fup", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nup", "nud", "ndr", "nul", "ndr", "ndl", "nur", "nlr", "nul", "nud", "nup", "nur", "ndl", "nur", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nul", "nud", "ndr", "nul", "ntl", "nlr", "nlr", "ndl", "ntl", "nlr", "nlr", "ntd", "nlt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ndl", "fup", "nur", "ndl", "nur", "ndl", "ndr", "nul", "nur", "ndl", "ndr", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "nlr", "nul", "ndr", "nul", "nur", "nlr", "slt", "nud", "nur", "ndl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "nlt", "ndr", "nlr", "nul", "ndr", "nlr", "nlr", "nlr", "ntr", "ndr", "nul", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "ndl", "nur", "nlr", "nlr", "nul", "ndr", "nlr", "ndl", "nud", "nud", "ndr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "ntd", "ndl", "ndr", "nlr", "nlr", "nul", "ndr", "nul", "fup", "nur", "ntd", "nlt", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nlr", "nlr", "sul", "nur", "nlr", "nlr", "glt", "nur", "nlr", "nlr", "nlr", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"12", "4", "f", "200"},
            {},
            {},
            {}
    };
}
