package com.ollum.mazecape.Arrays;

public class World3 {
    public static final String[][] SNOW_01 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nrt", "slr", "slr", "slr", "glt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"3", "3", "s", "1"},
            {},
            {}
    };
    public static final String[][] SNOW_02 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nrt", "nlr", "nlr", "sdl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "sdl", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "grt", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "sur", "nlr", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"3", "3", "s", "7"},
            {},
            {}
    };
    public static final String[][] SNOW_03 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "srt", "ndl", "gdn", "ndr", "slt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nrt", "ncs", "ncs", "ncs", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ncs", "ntr", "ntl", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ntl", "ncs", "ncs", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nul", "sup", "nur", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"3", "4", "s", "19"},
            {},
            {}
    };
    public static final String[][] SNOW_04 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ntu", "nlr", "nlr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nup", "nur", "nlr", "nlr", "nlr", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ntu", "ntu", "slr", "nlr", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nur", "nlr", "nlr", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "gud", "ntl", "nlr", "nlr", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ntl", "nlr", "slr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ntd", "tlr", "nlr", "nlr", "sul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"5", "3", "s", "11"},
            {},
            {"5,9"}
    };
    public static final String[][] SNOW_05 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "ntu", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ndl", "nud", "sdn", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "sdn", "nur", "ncs", "ntr", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ntu", "ncs", "ntd", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ncs", "ntr", "ndr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "sdn", "ntl", "ntd", "ncs", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ntd", "ndl", "nur", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "gup", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"5", "3", "s", "19"},
            {},
            {}
    };
    public static final String[][] SNOW_06 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "nlr", "ndl", "ndr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ntu", "nlr", "ncs", "ntr", "srt", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ncs", "nlr", "ncs", "ntd", "nlr", "plt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nrt", "ntr", "srt", "nul", "ndr", "ntu", "glt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ncs", "nlr", "ntu", "ntr", "nur", "plt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ntd", "nlr", "ncs", "ntr", "srt", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nlr", "nlr", "nul", "nur", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"3", "6", "s", "100"},
            {"9,5", "9,7"},
            {}
    };
    public static final String[][] SNOW_07 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ndl", "ndr", "ndl", "srt", "ntu", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ntd", "ncs", "ncs", "ndl", "ntl", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "gup", "ndr", "ncs", "ncs", "ncs", "ncs", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ncs", "ncs", "ncs", "ncs", "ncs", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ncs", "ncs", "ncs", "ncs", "ntr", "sdn", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ntr", "nur", "ncs", "ncs", "jcd", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ntd", "slt", "nur", "nul", "nur", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"6", "6", "s", "33"},
            {},
            {}
    };
    public static final String[][] SNOW_08 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ndl", "nrt", "ntu", "ndl", "srt", "ntu", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ntd", "ndl", "ntl", "ntd", "ndl", "ntl", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "sup", "ndr", "ncs", "nul", "ndr", "ncs", "nul", "ndn", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ntr", "nur", "ntu", "ntr", "nur", "ntu", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ntd", "ndl", "ntl", "ntd", "ndl", "ntl", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nup", "ndr", "ncs", "nul", "ndr", "ncs", "nul", "gdn", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ntr", "nur", "ntu", "ntr", "nur", "ntu", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ntd", "slt", "nur", "ntd", "nlt", "nur", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"6", "6", "s", "100"},
            {},
            {}
    };
    public static final String[][] SNOW_09 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "ndl", "ndr", "nlr", "slt", "ndr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "ncs", "ncs", "ntu", "nlr", "ncs", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "ntd", "ntr", "nur", "ndl", "nud", "ndr", "nlr", "nlr", "ndl", "ndr", "nlr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nrt", "ndl", "nud", "ndr", "nul", "nud", "nud", "ndr", "ndl", "nud", "ntl", "ntu", "ndl", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "ncs", "ncs", "ncs", "nlr", "nul", "nud", "nud", "nup", "ntl", "nul", "nud", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "ntl", "ncs", "ncs", "ntu", "ndl", "nud", "ntl", "ntu", "ncs", "ndl", "nud", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nud", "nud", "nud", "nud", "nud", "nud", "nur", "ncs", "ncs", "ncs", "nul", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nud", "nur", "nul", "nud", "nud", "gup", "ndn", "nud", "nud", "nud", "ndr", "ntr", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nud", "ndr", "nlr", "nul", "nup", "ndn", "nur", "ncs", "nul", "nud", "ntl", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nud", "ntl", "nlr", "ntu", "nlr", "ntd", "nlr", "ncs", "ndl", "nud", "nur", "ndl", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nud", "nud", "nrt", "ncs", "nlr", "nlr", "nlr", "ncs", "nul", "nur", "ndl", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nur", "ncs", "nlr", "ncs", "nlr", "nlr", "nlr", "ncs", "nlr", "ndl", "nud", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "nlr", "ncs", "nlr", "ncs", "nlr", "nlr", "nlr", "nul", "xxx", "nud", "nud", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nrt", "nlr", "ntd", "nlr", "nul", "srt", "nlr", "nlr", "nlr", "nlr", "ncs", "nul", "nup", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nul", "srt", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"10", "11", "s", "100"},
            {},
            {}
    };
}
