package com.ollum.mazecape.Arrays;

public class World4 {
    public static final String[][] DESERT_01 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ntu", "nlr", "nlr", "slt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "nlr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "sdn", "ndr", "nlr", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nud", "sdn", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nul", "gup", "nur", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"4", "3", "d", "39"},
            {},
            {}
    };
    public static final String[][] DESERT_02 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "nlr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "ndl", "srt", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "nul", "nur", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ndl", "ndr", "nlr", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "srt", "nul", "gup", "srt", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"5", "3", "d", "34"},
            {},
            {}
    };
    public static final String[][] DESERT_03 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "sdn", "ndr", "ntu", "nlt", "ndr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nul", "nud", "ndr", "nul", "sdn", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "nul", "nud", "ndr", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "ndl", "nur", "ntr", "ndr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nur", "nlr", "nul", "nur", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "ndr", "nlr", "ndl", "ndr", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nul", "nur", "glt", "nur", "nul", "sup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"5", "3", "d", "55"},
            {},
            {}
    };
    public static final String[][] DESERT_04 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "srt", "nlr", "ntu", "nlr", "nlr", "nlr", "nlt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "ncs", "nlr", "nlr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "nlt", "nur", "nlr", "nlr", "ndl", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ndl", "ndr", "nlr", "nlr", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "srt", "nul", "nur", "nlr", "nlr", "ndl", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "grt", "nlr", "nlr", "nlr", "mtu", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "srt", "nlr", "nlr", "nlr", "nul", "wrt", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"9", "3", "d", "71"},
            {},
            {}
    };
    public static final String[][] DESERT_05 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nrt", "nlr", "nlr", "ntu", "tlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "tlr", "ntd", "ndl", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "sup", "ndr", "nlr", "ndl", "cud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "sdn", "nud", "grt", "nul", "ntl", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ntd", "slt", "ndr", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nlr", "tlr", "ntd", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"3", "3", "d", "100"},
            {},
            {"7,3", "5,4", "5,8"}
    };
    public static final String[][] DESERT_06 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "srt", "nlr", "mtu", "ndl", "ndr", "nlr", "slt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "nul", "gup", "ntl", "ntu", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "ntu", "ntu", "ncs", "ntr", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "ntd", "ntd", "ntd", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ntu", "ntu", "ntu", "ntu", "ntu", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ntd", "nul", "nud", "nur", "ntd", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nlr", "wlt", "nup", "srt", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"6", "6", "d", "48"},
            {},
            {}
    };
    public static final String[][] DESERT_07 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "srt", "ndl", "ndr", "ntu", "ndl", "ndr", "slt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "prt", "ntr", "ntl", "mcs", "ntr", "ntl", "plt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nul", "pup", "gup", "pup", "nur", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "ndl", "ndr", "nlr", "ntu", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "nul", "nud", "wup", "xxx", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ndl", "nud", "sdn", "ndr", "nul", "nup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "prt", "nul", "nur", "nul", "nur", "nlr", "plt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"6", "3", "d", "56"},
            {"5,5", "3,9", "7,5", "9,9", "3,4", "9,4"},
            {}
    };
    public static final String[][] DESERT_08 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nrt", "ndl", "ndr", "nlr", "ndl", "ndr", "ndl", "ndr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nul", "nud", "ndr", "nul", "nud", "nur", "nul", "nrt", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "nul", "nur", "ntu", "ntr", "sdn", "ndr", "ndl", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "slt", "ndr", "nul", "fup", "nur", "nul", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "ntu", "nul", "ndr", "nlr", "ndl", "fdn", "nud", "gup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "nul", "nur", "ndl", "ntl", "ndl", "nur", "nul", "nur", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "nlr", "flt", "nud", "nud", "nur", "nlr", "nlr", "ndl", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "ndl", "nur", "ncs", "nlr", "nlt", "ndr", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nur", "ndl", "nud", "ndr", "ndl", "nur", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nul", "srt", "nul", "nur", "nul", "nur", "nlr", "nlr", "nlt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"12", "12", "d", "31"},
            {},
            {}
    };
    public static final String[][] DESERT_09 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "ntu", "ndl", "ndr", "nlr", "ntu", "ntu", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ndl", "nup", "nur", "nul", "nrt", "nul", "ntl", "nlt", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ntd", "flt", "ndn", "srt", "ndl", "nrt", "nul", "ndr", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ntu", "nlt", "nur", "ndl", "nud", "ndr", "nlt", "nud", "nup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "nlr", "ndl", "nud", "nur", "ntd", "ndl", "nur", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "srt", "nlr", "nul", "nud", "ndr", "nlr", "ntr", "fdn", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nlr", "ndl", "ndr", "nul", "nud", "ndn", "nur", "ntr", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ntu", "ntd", "nul", "ndr", "nul", "ntl", "ndl", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nup", "ntl", "ndl", "ndn", "nud", "srt", "ntr", "ntl", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nrt", "nul", "nur", "nul", "nur", "glt", "nup", "nur", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"6", "6", "d", "93"},
            {},
            {}
    };
}
