package com.ollum.mazecape.Arrays;

public class World3 {
    public static final String[][] SNOW_01 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "slr", "slr", "slr", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "s", "1"},
            {},
            {}
    };
    public static final String[][] SNOW_02 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nlr", "nlr", "sdl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "sdl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "grt", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sur", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "3", "s", "7"},
            {},
            {}
    };
    public static final String[][] SNOW_03 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "srt", "ndl", "gdn", "vdr", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "vcs", "vcs", "vcs", "vdl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ncs", "ntr", "vtl", "vul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ltl", "ncs", "ncs", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nul", "sup", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "4", "s", "19"},
            {},
            {}
    };
    public static final String[][] SNOW_04 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntu", "nlr", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nup", "nur", "nlr", "nlr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntu", "ntu", "slr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "nlr", "nlr", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "gud", "ntl", "nlr", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ntl", "nlr", "slr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntd", "tlr", "nlr", "nlr", "sul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"5", "3", "s", "11"},
            {},
            {"5,9"}
    };
    public static final String[][] SNOW_05 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ntu", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ndl", "nud", "sdn", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sdn", "nur", "ncs", "ntr", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntu", "ncs", "ntd", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ncs", "ntr", "ndr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sdn", "ntl", "ntd", "ncs", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntd", "ndl", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "xxx", "xxx", "gup", "xxx", "xxx", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"5", "3", "s", "19"},
            {},
            {}
    };
    public static final String[][] SNOW_06 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "nlr", "ndl", "ndr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntu", "nlr", "ncs", "ntr", "srt", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ncs", "nlr", "ncs", "ntd", "nlr", "plt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "ntr", "srt", "nul", "ndr", "ntu", "glt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ncs", "nlr", "ntu", "ntr", "nur", "plt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntd", "nlr", "ncs", "ntr", "srt", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nlr", "nul", "nur", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "6", "s", "33"},
            {"9,5", "9,7"},
            {}
    };
    public static final String[][] SNOW_07 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ndl", "ndr", "ndl", "srt", "ntu", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntd", "ncs", "ncs", "ndl", "ntl", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "gup", "ndr", "ncs", "ncs", "ncs", "ncs", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ncs", "ncs", "ncs", "ncs", "ncs", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ncs", "ncs", "ncs", "ncs", "ntr", "sdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntr", "nur", "ncs", "ncs", "jcd", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntd", "slt", "nur", "nul", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"6", "6", "s", "33"},
            {},
            {}
    };
    public static final String[][] SNOW_08 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntu", "ntu", "ntu", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "stl", "nlr", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ntl", "ncs", "ncs", "ntu", "ntr", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ncs", "ncs", "gcs", "ncs", "ntr", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "sup", "nud", "nup", "nud", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "ncs", "ntu", "ntr", "ntl", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nrt", "nlr", "nul", "nur", "ntd", "ntd", "slt", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"3", "9", "s", "20"},
            {},
            {}
    };
    public static final String[][] SNOW_09 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ndl", "nrt", "ntu", "ndl", "srt", "ntu", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntd", "ndl", "ntl", "ntd", "ndl", "ntl", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "sup", "ndr", "ncs", "nul", "ndr", "ncs", "nul", "ndn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntr", "nur", "ntu", "ntr", "nur", "ntu", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ntl", "ntd", "ndl", "ntl", "ntd", "ndl", "ntl", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nup", "ndr", "ncs", "nul", "ndr", "ncs", "nul", "gdn", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "ntr", "nur", "ntu", "ntr", "nur", "ntu", "ntr", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "ntd", "slt", "nur", "ntd", "nlt", "nur", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"6", "6", "s", "34"},
            {},
            {}
    };
    public static final String[][] SNOW_10 = {
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "oul", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "oup", "our", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "ndr", "nlr", "ndl", "ndr", "nlr", "slt", "ndr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ncs", "ncs", "ntu", "nlr", "ncs", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "ntd", "ntr", "nur", "ndl", "nud", "ndr", "nlr", "nlr", "ndl", "ndr", "nlr", "nlr", "ndl", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nrt", "ndl", "nud", "ndr", "nul", "nud", "nud", "ndr", "ndl", "nud", "ntl", "ntu", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "ndr", "ncs", "ncs", "ncs", "nlr", "nul", "nud", "nud", "nup", "ntl", "nul", "nud", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "ntl", "ncs", "ncs", "ntu", "ndl", "nud", "ntl", "ntu", "ncs", "ndl", "nud", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "nud", "nud", "nud", "nud", "nud", "nur", "ncs", "ncs", "ncs", "nul", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "nur", "nul", "nud", "nud", "gup", "ndn", "nud", "nud", "nud", "ndr", "ntr", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "ndr", "nlr", "nul", "nup", "ndn", "nur", "ncs", "nul", "nud", "ntl", "nul", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "ntl", "nlr", "ntu", "nlr", "ntd", "nlr", "ncs", "ndl", "nud", "nur", "ndl", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nud", "nud", "nrt", "ncs", "nlr", "nlr", "nlr", "ncs", "nul", "nur", "ndl", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nud", "nur", "ncs", "nlr", "ncs", "nlr", "nlr", "nlr", "ncs", "nlr", "ndl", "nud", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nur", "nlr", "ncs", "nlr", "ncs", "nlr", "nlr", "nlr", "nul", "xxx", "nud", "nud", "nud", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nud", "nrt", "nlr", "ntd", "nlr", "nul", "srt", "nlr", "nlr", "nlr", "nlr", "ncs", "nul", "nup", "nud", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "olt", "nur", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nlr", "nul", "srt", "nlr", "nul", "ort", "ocs", "ocs"},
            {"ocs", "ocs", "odl", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odn", "odr", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs", "ocs"},
            {"10", "11", "s", "100"},
            {},
            {}
    };
}
