package com.ollum.mazecape.Arrays;

public class World2 {
    public static final String[][] CAVE_01 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "sup", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "sup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "sup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "glt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"3", "3", "c", "26"},
            {},
            {}
    };
    public static final String[][] CAVE_02 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndn", "srt", "nlr", "ntu", "nlt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "ntu", "ncs", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nul", "nup", "nud", "sup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "nlr", "ntd", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nlr", "glt", "frt", "sul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"3", "3", "c", "30"},
            {},
            {}
    };
    public static final String[][] CAVE_03 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "ndl", "ndr", "nlr", "ntu", "ntu", "nlr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "srt", "nul", "nur", "ndl", "nur", "ntr", "sdn", "ndr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ndl", "ndr", "slt", "ntl", "ndl", "nur", "nul", "nud", "ndn", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ntd", "nul", "ndr", "ntr", "nur", "flt", "ndr", "ntd", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nlr", "nlr", "nul", "nur", "nlt", "nrt", "ntd", "nlr", "glt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"3", "3", "c", "57"},
            {},
            {}
    };
    public static final String[][] CAVE_04 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nrt", "ntu", "ndl", "ndr", "ndl", "ndr", "glt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nul", "ttl", "nul", "nup", "nud", "sdn", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ndl", "nur", "ndl", "nrt", "ntr", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndn", "nud", "ndr", "nul", "sdn", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nur", "ndl", "nud", "ttl", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "nul", "sdn", "ntl", "nul", "ntl", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nlr", "nul", "nur", "nlr", "nul", "nup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"3", "6", "c", "51"},
            {},
            {"5,4", "8,7"}
    };
    public static final String[][] CAVE_05 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "nlr", "ftu", "nlr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nlr", "ndl", "mud", "ndr", "ndl", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ndl", "sup", "nud", "wup", "nur", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "ndl", "ntl", "clr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "sdn", "nud", "nur", "nlr", "slt", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "ttd", "nlr", "ndl", "ndr", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nlr", "nlr", "glt", "nur", "nul", "fup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"6", "3", "c", "100"},
            {},
            {"5,8"}
    };
    public static final String[][] CAVE_06 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nrt", "ndl", "prt", "nlr", "wlr", "nlr", "sdl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndn", "ntl", "nlr", "nlr", "plt", "ndn", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "fud", "ntl", "nlt", "ndr", "tlr", "sul", "pup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nup", "prt", "ntd", "plt", "prt", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "sud", "ndr", "ntu", "ndl", "prt", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nul", "pur", "ctd", "mlr", "nlr", "glt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"3", "3", "c", "100"},
            {"7,4", "9,5", "5,3", "8,6", "7,7", "7,6", "5,6", "5,9"},
            {"7,5"}
    };
    public static final String[][] CAVE_07 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ndl", "ndr", "nlr", "ndl", "sdn", "ndr", "ntu", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "sup", "nud", "ndr", "nul", "nud", "ntl", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ndl", "nud", "nur", "nlr", "ntr", "nur", "ndl", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nud", "ndr", "ndl", "nud", "ndr", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nud", "ntl", "ncs", "nul", "nud", "ndr", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "nul", "nur", "ntr", "ndr", "nul", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndn", "ndr", "ndl", "nud", "nud", "ndr", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ncs", "nul", "nud", "nup", "nud", "nup", "grt", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nrt", "ntd", "nlr", "ntd", "nlr", "ftd", "nlr", "nlr", "slt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"7", "7", "c", "70"},
            {},
            {}
    };
    public static final String[][] CAVE_08 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "sdn", "ndn", "wdn", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ccs", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ccs", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ccs", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "mud", "tud", "sup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ccs", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ccs", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "gul", "sup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"4", "3", "c", "100"},
            {},
            {"4,7"}
    };
    public static final String[][] CAVE_09 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nrt", "nlr", "ntu", "nlr", "plt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "plt", "cud", "prt", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nlr", "ntd", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "srt", "nlr", "ttu", "nlr", "plt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "prt", "ndl", "ntl", "nlr", "plt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "wrt", "nul", "nur", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "prt", "nlr", "mtu", "nlt", "sup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "srt", "plt", "pup", "prt", "glt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"3", "3", "c", "100"},
            {"7,3", "4,10", "4,4", "3,7", "6,4", "7,7", "7,6", "3,9", "5,10", "6,10"},
            {"5,6"}
    };
    public static final String[][] CAVE_10 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nrt", "nlr", "mtu", "ntu", "nlr", "nlt", "pdn", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "wdn", "gdn", "nud", "nud", "ndr", "slt", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "nul", "tud", "nur", "nlr", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "nlr", "tlr", "ncs", "tlr", "nlr", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "nlr", "ndl", "tud", "ndr", "ndl", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "srt", "nul", "nud", "nud", "sup", "nup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "pup", "nrt", "nlr", "ntd", "ntd", "nlr", "nlt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"6", "6", "c", "56"},
            {"3,9", "9,3"},
            {"6,5", "5,6", "7,6", "6,7"}
    };
    public static final String[][] CAVE_11 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ntu", "nlr", "nlr", "nlt", "ndr", "nlr", "nlr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nup", "nud", "ndr", "ndl", "ndr", "ntd", "flt", "ndr", "ndl", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ntr", "nud", "nur", "nul", "ndr", "ntu", "nul", "nur", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nup", "nur", "ndl", "ndr", "ntr", "nup", "ndr", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ndl", "ndr", "nul", "nud", "fup", "ndr", "nul", "sdn", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nur", "ndl", "nur", "nlr", "ntd", "nlr", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "sup", "nud", "ndr", "nul", "ndr", "nlr", "ndl", "ndr", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nul", "nur", "ndl", "nud", "srt", "nul", "ntl", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "nlr", "ndl", "nud", "nud", "ndr", "ndl", "nur", "flt", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "flt", "nur", "ntd", "nul", "gup", "nur", "nlr", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"7", "3", "c", "114"},
            {},
            {}
    };
    public static final String[][] CAVE_12 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "ntu", "nlr", "nlr", "ndl", "ndr", "nlr", "nlr", "ntu", "nlr", "ntu", "nlt", "ndr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nrt", "ntd", "nlt", "ndn", "nur", "ncs", "nlr", "ntu", "ntd", "nlt", "nup", "ndr", "ntr", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ntu", "nlr", "nlt", "nud", "nrt", "ntr", "nrt", "ntr", "ndr", "nlr", "ndl", "nud", "nup", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nrt", "ntd", "ntu", "nlr", "ncs", "nlt", "ntl", "nlt", "nup", "nud", "nrt", "ntd", "ntr", "ndr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "nul", "nrt", "nul", "ndr", "nul", "ndn", "ndr", "ntd", "nlt", "ndr", "ncs", "ntr", "ndn", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nup", "ndr", "nlr", "nlr", "ntu", "nul", "ndr", "nul", "nud", "ndr", "nlr", "ntr", "nud", "nur", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ntr", "nrt", "ndl", "nur", "ntu", "nul", "ndr", "ntr", "nup", "ndr", "nul", "nud", "ndr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ntl", "nlr", "nul", "nrt", "nul", "ndr", "nul", "nup", "ndr", "ntr", "ndr", "nul", "ntl", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ntl", "nlr", "ntu", "nlr", "ntu", "nul", "ndr", "ndl", "nup", "ntl", "nul", "ndr", "ntr", "nup", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ntd", "ndl", "nud", "ndn", "nud", "nrt", "ntr", "nur", "slt", "ntl", "ndl", "nud", "nud", "ndn", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nlr", "ntr", "ntl", "ntr", "ntl", "nlt", "ntl", "nlt", "ndr", "nul", "nud", "nud", "nur", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "ntd", "nul", "nur", "ntr", "ndr", "nul", "ndn", "nud", "ndn", "nud", "nur", "nlr", "glt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "ndr", "ntu", "ndl", "nur", "ntr", "ndr", "ntr", "nur", "ntd", "ncs", "nlr", "ndl", "sdn", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ntd", "nul", "nud", "nur", "ndl", "nur", "ntr", "nur", "ndl", "ndn", "nud", "ndr", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nlr", "nlr", "nul", "nrt", "ntd", "slt", "nur", "nlr", "nul", "nur", "ntd", "ntd", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"3", "8", "c", "147"},
            {},
            {}
    };
    public static final String[][] CAVE_13 = {
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "ntu", "nlt", "ndr", "nlr", "nlr", "nlr", "nlr", "ndl", "nrt", "nlr", "ndl", "ndr", "nlr", "nlr", "nlr", "ntu", "nlr", "nlr", "flt", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nup", "ndr", "nul", "ndr", "ntu", "nlr", "ndl", "ntl", "nlr", "ndl", "nud", "nur", "nlr", "ndl", "ndn", "nur", "ndl", "ndr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "nul", "nrt", "nul", "nur", "ndl", "nud", "nur", "ndl", "nup", "nur", "ndl", "ndn", "nur", "ntr", "ndn", "nur", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "nlr", "nlr", "nlr", "nlr", "nul", "nud", "ndr", "ntr", "ndr", "nlr", "nul", "ntl", "nlt", "nur", "ntd", "ndl", "ndn", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "nlr", "nlr", "ntu", "nlr", "flt", "nud", "nud", "nup", "nur", "nlr", "ndl", "nur", "nlr", "ntu", "nlr", "ntd", "nul", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "nlr", "ndl", "nur", "nlr", "nlr", "nul", "nud", "ndr", "nlr", "ndl", "nur", "nlr", "ndl", "nud", "ndn", "ndr", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ntu", "ndl", "nur", "nlr", "nlr", "ndl", "fdn", "nud", "ntl", "flt", "nur", "nlr", "ndl", "nud", "nur", "ntr", "nur", "nlr", "ndl", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nud", "nup", "ndr", "nlr", "nlr", "nul", "nud", "nur", "nul", "ndr", "nlr", "ndl", "nud", "nud", "nrt", "ntd", "nlr", "slt", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "nlr", "nul", "ndr", "nlr", "nlr", "ntr", "ndr", "nlr", "nul", "sdn", "nur", "ntr", "nur", "nlr", "nlr", "nlr", "ndl", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "ndl", "ndr", "nul", "nrt", "ndl", "nud", "nur", "nlr", "ndl", "nur", "ndl", "nur", "nlr", "nlr", "nlr", "ndl", "nur", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nup", "ntl", "nul", "nrt", "ntu", "ntr", "nur", "ntu", "ndl", "nur", "ndl", "ntl", "ndl", "ndr", "nlr", "ndl", "nud", "ndr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ndl", "nur", "nlr", "nlr", "nul", "nur", "ndl", "nud", "nur", "ndl", "nud", "nup", "nur", "ntd", "ndl", "nur", "nul", "nud", "fdn", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndn", "nud", "ndr", "ndl", "ndr", "ndl", "srt", "nul", "nud", "ndr", "nul", "nur", "nlr", "nlr", "ndl", "nur", "nlr", "ndl", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "nul", "nur", "nul", "nud", "ndr", "nlr", "nul", "nud", "ndr", "nlt", "ndr", "nlr", "nul", "frt", "ndl", "nud", "nur", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ntl", "ntu", "nlr", "flt", "ndr", "nul", "nud", "ndr", "ndl", "ntl", "nul", "ndr", "nul", "nrt", "ntu", "ndl", "nud", "nud", "ndr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "nur", "ndl", "ndr", "nul", "ndr", "nul", "nud", "nur", "nul", "ndr", "nul", "nrt", "ntu", "nul", "nur", "nul", "nud", "nud", "ndn", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "ndl", "nud", "nud", "ndr", "ntd", "ndl", "nud", "fdn", "ndr", "nul", "ndr", "ndl", "nur", "ndl", "ndr", "ndl", "nud", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "ndr", "nul", "nur", "nul", "nud", "ndr", "nul", "nur", "ntr", "nur", "nlr", "nul", "nur", "ndl", "nur", "nul", "nur", "nul", "nud", "nud", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nud", "ndr", "nlr", "ndl", "nup", "nud", "ndr", "nlt", "nud", "nrt", "ntu", "ndl", "ndr", "nul", "ndr", "nlr", "nlr", "ndl", "nur", "ntr", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "nur", "nul", "nrt", "ntd", "nlr", "nul", "nur", "nlr", "ntd", "nlr", "nul", "gup", "nur", "nlr", "ntd", "nlr", "flt", "nur", "nlr", "nul", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx", "xxx"},
            {"12", "3", "c", "400"},
            {},
            {}
    };
}
